In [3]:
import pandas as pd
import numpy as np

In [5]:
#imported dataset for the project

df_airbnb = pd.read_csv("/content/sample_data/airbnb.csv", encoding = 'latin1')

In [6]:
display(df_airbnb)

,Unnamed: 0,id,name,rating,reviews,host_name,host_id,address,features,amenities,...,price,country,bathrooms,beds,guests,toiles,bedrooms,studios,checkin,checkout
0,0,49849504,Perla bungalov,4.71,64,Mehmetcan,357334205.0,"Kartepe, Kocaeli, Turkey","2 guests,2 bedrooms,1 bed,1 bathroom","Mountain view,Valley view,Lake access,Kitchen,...",...,8078,Turkey,1,1,2,0,2,0,Flexible,12 00 pm
1,1,50891766,Authentic Beach Architect Sheltered Villa with...,New,0,Fatih,386223873.0,"KaÅ, Antalya, Turkey","4 guests,2 bedrooms,2 beds,2 bathrooms","Kitchen,Wifi,Dedicated workspace,Free parking ...",...,4665,Turkey,2,2,4,0,2,0,4 00 pm - 11 00 pm,10 00 am
2,2,50699164,cottages sataplia,4.85,68,Giorgi,409690853.0,"Imereti, Georgia","4 guests,1 bedroom,3 beds,1 bathroom","Mountain view,Kitchen,Wifi,Dedicated workspace...",...,5991,Georgia,1,3,4,0,1,0,After 1 00 pm,12 00 pm
3,3,49871422,Sapanca Breathable Bungalow,5.0,13,Melih,401873242.0,"Sapanca, Sakarya, Turkey","4 guests,1 bedroom,2 beds,1 bathroom","Mountain view,Valley view,Kitchen,Wifi,Free pa...",...,11339,Turkey,1,2,4,0,1,0,After 2 00 pm,12 00 pm
4,4,51245886,Bungalov Ev 2,New,0,Arp Sapanca,414884116.0,"Sapanca, Sakarya, Turkey","2 guests,1 bedroom,1 bed,1 bathroom","Kitchen,Wifi,Free parking on premises,TV,Air c...",...,6673,Turkey,1,1,2,0,1,0,After 2 00 pm,12 00 pm
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12800,12800,44697740,"Brown Dome House No. 3, full of healing",4.94,16,Aidan,161552316.0,"Imhoe-myeon, Jindo, South Jeolla Province, Sou...","4 guests,8 bathrooms","Kitchen,Wifi,Free parking on premises,Private ...",...,4288,South Korea,8,0,4,0,0,0,3 00 pm - 11 00 pm,11 00 am
12801,12801,29975283,Bubble Hotel Ubud with Bathtub under the Sky,4.67,6,Martha,118954227.0,"Gianyar, Indonesia","2 guests,1 bedroom,1 bed,Toilet with sink","Wifi,Free on-street parking,Air conditioning,G...",...,15200,Indonesia,0,1,2,1,1,0,3 00 pm - 10 00 pm,12 00 pm
12802,12802,32977697,Paradise Eco Hub,4.67,3,Silas,175214568.0,"Kabale, Uganda","2 guests,1 bedroom,2 beds,1 private bathroom","Wifi,Breakfast,Long-term stays allowed,Unavail...",...,9103,Uganda,1,2,2,0,1,0,After 3 00 pm,NaN
12803,12803,8006146,WisDOME - Mentigi Bay Village - Gilis - Lombok,4.86,7,Cempaka,718423.0,"Gunung Sari, Nusa Tenggara Barat, Indonesia","8 guests,2 bedrooms,4 beds,2.5 bathrooms","Kitchen,Wifi,Dedicated workspace,Free parking ...",...,42262,Indonesia,2,4,8,0,2,0,Flexible,12 00 pm
12804,12804,40547903,Enjoy Vitamin SEA! Ocean Front! [Ocean's Seven],4.85,13,Achy,246470880.0,"Uruma, Okinawa, Japan","5 guests,1 bedroom,2 beds,1 bathroom","Sea view,Beach access â Beachfront,Kitchen,W...",...,9909,Japan,1,2,5,0,1,0,After 4 00 pm,11 00 am

In [7]:
#run all database to show there are no memory issues

low_memory = False

In [8]:
display(df_airbnb.shape) #describe number of lines and columns

(12805, 23)

In [9]:
display(df_airbnb.info()) #describe the database with its columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12805 entries, 0 to 12804
Data columns (total 23 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0    12805 non-null  int64
 1   id            12805 non-null  int64
 2   name          12805 non-null  object
 3   rating        12805 non-null  object
 4   reviews       12805 non-null  object
 5   host_name     12797 non-null  object
 6   host_id       12805 non-null  float64
 7   address       12805 non-null  object
 8   features      12805 non-null  object
 9   amenities     12805 non-null  object
 10  safety_rules  12805 non-null  object
 11  hourse_rules  12805 non-null  object
 12  img_links     12805 non-null  object
 13  price         12805 non-null  int64
 14  country       12805 non-null  object
 15  bathrooms     12805 non-null  int64
 16  beds          12805 non-null  int64
 17  guests        12805 non-null  int64
 18  toiles        12805 non-null  int64
 19  bedrooms      12805 non-null  int64
 20  studios       12805 non-null  int64
 21  checkin       12005 non-null  object
 22  checkout      10355 non-null  object
dtypes: float64(1), int64(9), object(13)
memory usage: 2.2+ MB

None

In [10]:
df_airbnb['checkout'] = df_airbnb['checkout'].fillna("-")

In [11]:
df_airbnb = df_airbnb.drop_duplicates()

df_airbnb['country'] = df_airbnb['country'].astype(str).str.strip()

In [12]:
#Questions for the project?

#1 Which countries are most represented on the platform, and how does the average price vary among them?

df_places_country = df_airbnb.groupby('country')['id'].count().reset_index(name = 'number_places')

df_places_country = df_places_country.sort_values(by = 'number_places', ascending =False) #India, Italy and Greece are Top3

top_3_countries = df_places_country.head(3)

display(top_3_countries)

df_avg_price = df_airbnb.groupby('country')['price'].mean().astype(int).reset_index(name = 'avg_price')


df_avg_price = df_avg_price.sort_values(by = 'avg_price', ascending = True)


#Top5 cheapest countries by avg price
display(df_avg_price.head(5))


#Top5 most expensive countries by avg price
display(df_avg_price.tail(5))

   country  number_places
43   India           2779
48   Italy           1187
35  Greece            889

    country  avg_price
90  Senegal       1289
10  Bolivia       2462
72    Nepal       2494
23     Cuba       2635
88   Rwanda       2776

                  country  avg_price
86                  Qatar     112717
6                 Bahamas     116397
111  United Arab Emirates     119633
39               Honduras     140998
92             Seychelles     155225

In [13]:
df_country_analysis = (
    df_airbnb
    .groupby('country')
    .agg(
        number_places=('id', 'count'),
        avg_price=('price', lambda x: x.mean().round().astype(int))
    )
    .reset_index()
    .sort_values(by='number_places', ascending=False)
)

display(df_country_analysis)

                  country  number_places  avg_price
43                  India           2779       7537
48                  Italy           1187      31636
35                 Greece            889      31432
106              Thailand            683      21021
108                Turkey            522      32863
..                    ...            ...        ...
90                Senegal              1       1289
101  Svalbard & Jan Mayen              1      14865
100             St Martin              1       8879
116               Vanuatu              1      15718
118        Ã
land Islands              1       5301

[119 rows x 3 columns]

In [14]:
#2 What is the difference in average price between properties that offer amenities like a pool or pet-friendly policies versus those that do not?

df_airbnb['amenities'] = df_airbnb['amenities'].astype(str)

filter_pool_petfriend = df_airbnb['amenities'].str.contains('Pool|Pet', case = False, na = False)

pool_petfriend_avg_price = df_airbnb[filter_pool_petfriend]['price'].mean().round().astype(int)
nopool_nopetfriend_avg_price = df_airbnb[~filter_pool_petfriend]['price'].mean().round().astype(int)

print(f"Average price for places with pool or petfriendly is {pool_petfriend_avg_price} in face of other places with average {nopool_nopetfriend_avg_price}")

Average price for places with pool or petfriendly is 21110 in face of other places with average 13608

In [15]:
price_diff = pool_petfriend_avg_price - nopool_nopetfriend_avg_price
pct_diff = round((price_diff / nopool_nopetfriend_avg_price) * 100, 1)

print(f"Absolute difference: {price_diff} ({pct_diff}% higher)")

Absolute difference: 7502 (55.1% higher)

In [16]:
#3 Does the rating score have significant impact on price?

#convert rating for a number

df_airbnb['rating_number'] = pd.to_numeric(df_airbnb['rating'], errors = 'coerce')

#correlation between rating and price

correlation = df_airbnb['rating_number'].corr(df_airbnb['price'])

#create rating groups to avaliate avg price and median

bins = [0,4.5, 4.8, 5.0]
labels = ['Below 4.5', '4.5-4.8', '4.8-5.0']
df_airbnb['rating_group'] = pd.cut(df_airbnb['rating_number'], bins=bins, labels=labels)

price_by_rating = (
    df_airbnb
    .groupby('rating_group', observed = False)['price']
    .agg(
        total_listings='count',
        avg_price=lambda x: x.mean().round().astype(int),
        median_price=lambda x: x.median()
    )
    .reset_index()
)

display(price_by_rating)

##Key Finding on Ratings vs. Price:
##At first glance, listings with the lowest ratings (< 4.0) appear to have a significantly higher average price (~25,026).
##However, deeper inspection reveals this is heavily affected by extreme outliers, creating some distortion in the analysis.
##Comparing median prices, evidence shows that low-rated properties perform quite similarly to top-rated ones, confirming that review scores do not dictate daily rates.

  rating_group  total_listings  avg_price  median_price
0    Below 4.5              64      14789        9095.0
1      4.5-4.8            2596      11184        6360.0
2      4.8-5.0            5907      14378        8952.0

In [35]:
#4 What is the proportion of listings managed by multi-property hosts versus single-property hosts, and do their pricing strategies differ?

host_count = df_airbnb['host_id'].value_counts() ##counts how many times a host appears

multi_host = host_count[host_count > 1].index

df_airbnb['host_type'] = np.where(df_airbnb['host_id'].isin(multi_host), 'Multi-property Host', 'Single-property Host')

host_comparison = (
    df_airbnb
    .groupby('host_type')
    .agg(
        total_listings=('id', 'count'),
        percentage=('id', lambda x: round((len(x) / len(df_airbnb)) * 100, 1)),
        avg_price=('price', lambda x: int(round(x.mean()))),
        median_price=('price', lambda x: int(round(x.median())))
    )
    .reset_index()
)

display(host_comparison)

#Although multi-property hosts hold higher average price, the median of the price and their share in the listings describe a different approach,
#much more concentrated on single-property hosts that present higher median price. In general, average prices do not differ so much which may sign a more open negotiation point (more competitive volume-driven pricing) with multiple hosts.

              host_type  total_listings  percentage  avg_price  median_price
0   Multi-property Host            3882        30.3      18931          7942
1  Single-property Host            8923        69.7      17161          8211

In [37]:
#5 How does the 'cost per guest' metric behave as the capacity (bedrooms and allowed guests) increases?

# 1. Ensure valid guest count and engineer 'price_per_guest'
df_valid = df_airbnb[df_airbnb['guests'] > 0].copy()
df_valid['price_per_guest'] = df_valid['price'] / df_valid['guests']

# 2. Cost per guest grouped by allowed guests
guest_cost_summary = (
    df_valid
    .groupby('guests')
    .agg(
        total_listings=('id', 'count'),
        avg_price_per_guest=('price_per_guest', lambda x: int(round(x.mean()))),
        median_price_per_guest=('price_per_guest', lambda x: int(round(x.median()))),
        avg_total_price=('price', lambda x: int(round(x.mean())))
    )
    .reset_index()
)

# 3. Cost per guest grouped by bedrooms
bedroom_cost_summary = (
    df_valid
    .groupby('bedrooms')
    .agg(
        total_listings=('id', 'count'),
        avg_price_per_guest=('price_per_guest', lambda x: int(round(x.mean()))),
        median_price_per_guest=('price_per_guest', lambda x: int(round(x.median()))),
        avg_total_price=('price', lambda x: int(round(x.mean())))
    )
    .reset_index()
)

display(guest_cost_summary.head(8))
display(bedroom_cost_summary.head(8))


##Economies of Scale in Groups: listings for 3–6 guests delivers the highest cost efficiency per person, reducing median cost per guest from 2,727 (couples) to 1,624–1,974 (30–40% savings).
##Large Property: Expanding bedroom capacity past 4 bedrooms increases cost per guest up to 3,113, as listings transition from standard apartments to high-end villas.

,guests,total_listings,avg_price_per_guest,median_price_per_guest,avg_total_price
0,1,127,4266,2307,4266
1,2,3729,4097,2727,8195
2,3,1228,2514,1624,7543
3,4,2607,2717,1974,10869
4,5,702,2573,1893,12867
5,6,1471,3237,1957,19421
6,7,253,2316,1947,16212
7,8,732,3655,2117,29236

,bedrooms,total_listings,avg_price_per_guest,median_price_per_guest,avg_total_price
0,0,692,2870,1992,8482
1,1,6374,3257,2063,8595
2,2,2377,2897,1982,13771
3,3,1406,3444,2151,23156
4,4,772,3692,2237,32561
5,5,420,4877,2513,51797
6,6,251,4031,2589,48081
7,7,135,4532,3113,66376